### ISSUE TITLE
To Implement form validation

### ISSUE THREAD

**Issue by syedsaadh** [syedsaadh/NiceLogin#1]

**Comment by akhil117** [comment]
I want to work on this one.

**Comment by akhil117** [comment]
check this one https://github.com/syedsaadh/NiceLogin/pull/2

**Comment by akhil117** [comment]
I had made few changes for form validation

**Comment by syedsaadh** [comment]
@akhil117 great to have your contribution. But could you please be more specific towards form validation. I mean to say email pattern validation and min character for password. Also instead of alert can you be more intutive and display alert within form container.

**Comment by akhil117** [comment]
Yeah sure.

**Comment by akhil117** [comment]
Could you check this https://github.com/syedsaadh/NiceLogin/pull/2

**Comment by akhil117** [comment]
I added some changes like email pattern, password the things like minimum characters..... and also display the message with in the corner(like for invalid input).

**Comment by syedsaadh** [comment]
Fixed #2
